# Generated by Django 3.2.6 on 2025-04-18 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('svg_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_out_order', models.IntegerField()),
                ('part_number', models.CharField(max_length=100)),
                ('usage_name', models.CharField(max_length=200)),
                ('unit_qty', models.PositiveIntegerField()),
                ('lr', models.CharField(blank=True, max_length=10, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('nn_note', models.TextField(blank=True, null=True)),
                ('child_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='motorpartsdata.childtitle')),
            ],
        ),
        migrations.CreateModel(
            name='ParentTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('serial_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_titles', to='motorpartsdata.serialnumber')),
            ],
        ),
        migrations.AddField(
            model_name='childtitle',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_titles', to='motorpartsdata.parenttitle'),
        ),
    ]
