# Generated by Django 5.1.6 on 2025-07-02 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpartsdata', '0002_alter_part_unit_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replacement', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.CharField(blank=True, max_length=100, null=True)),
                ('oldest', models.CharField(blank=True, max_length=100, null=True)),
                ('range_code', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_code', models.CharField(blank=True, max_length=100, null=True)),
                ('class_code', models.CharField(blank=True, max_length=100, null=True)),
                ('vat_code', models.CharField(blank=True, max_length=100, null=True)),
                ('list_price', models.CharField(blank=True, max_length=100, null=True)),
                ('vor', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_order', models.CharField(blank=True, max_length=100, null=True)),
                ('replacement_code', models.CharField(blank=True, max_length=100, null=True)),
                ('whs', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_available', models.CharField(blank=True, max_length=100, null=True)),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_data', to='motorpartsdata.part')),
            ],
        ),
    ]
