# Generated by Django 4.2.23 on 2025-07-31 14:13

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('motorpartsdata', '0004_shippingaddress_shippingmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='countries',
            field=django_countries.fields.CountryField(max_length=752, multiple=True),
        ),
    ]
