# Generated by Django 4.2.23 on 2025-08-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpartsdata', '0005_alter_shippingmethod_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialnumber',
            name='vehicle_brand',
            field=models.CharField(default='Maxus', help_text='Vehicle brand (Maxus, Peugeot, Renault, etc.)', max_length=100),
        ),
    ]
