# Generated by Django 4.2.23 on 2025-08-13 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('motorpartsdata', '0006_serialnumber_vehicle_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceUpdateTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(db_index=True, help_text='Product SKU/UPC that was updated', max_length=100)),
                ('price_updated', models.BooleanField(default=True, help_text='Flag indicating this product was updated')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Previous price before update', max_digits=12, null=True)),
                ('new_price', models.DecimalField(decimal_places=2, help_text='New price after update', max_digits=12)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when price was updated')),
                ('excel_filename', models.CharField(help_text='Name of Excel file used for update', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the price update')),
                ('updated_by', models.CharField(blank=True, help_text='User who performed the update', max_length=100)),
            ],
            options={
                'verbose_name': 'Price Update Tracker',
                'verbose_name_plural': 'Price Update Trackers',
                'ordering': ['-update_date'],
                'indexes': [models.Index(fields=['product_sku'], name='motorpartsd_product_fb811f_idx'), models.Index(fields=['update_date'], name='motorpartsd_update__e0232b_idx'), models.Index(fields=['price_updated'], name='motorpartsd_price_u_e06f9f_idx')],
            },
        ),
    ]
