# Generated by Django 4.2.23 on 2025-08-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpartsdata', '0007_priceupdatetracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingdata',
            name='price_updated',
            field=models.BooleanField(default=False),
        ),
    ]
