# Generated by Django 4.2.23 on 2025-09-17 12:33

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('motorpartsdata', '0008_pricingdata_price_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='oscar_imported',
            field=models.BooleanField(default=False, help_text='Tracks if this part has been imported to Oscar'),
        ),
        migrations.AddField(
            model_name='part',
            name='oscar_imported_at',
            field=models.DateTimeField(blank=True, help_text='When this part was imported to Oscar', null=True),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='countries',
            field=django_countries.fields.CountryField(max_length=4, multiple=True),
        ),
    ]
